// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbbydksdotfjpzrqnjoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiYnlka3Nkb3RmanB6cnFuam9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODAwNDksImV4cCI6MjA2NTA1NjA0OX0.89Y-yFhfweoEXyPM_XJhuvUcQf_q9DK-k_k4VtiC0xE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);